src/Entity/Commentaire.php
<?php

namespace App\Entity;

use App\Repository\CommentaireRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Form\FormTypeInterface;

/**
 * @ORM\Entity(repositoryClass=CommentaireRepository::class)
 */
class Commentaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="date")
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $auteur;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom_crypto;

    /**
     * @ORM\PrePersist()
     */
    public function prePersist()
    {
        $this->date = new \DateTime();
    }
    /**
     * @ORM\PreUpdate()
     */
    public function preUpdate()
    {
        $this->date = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDate(): ?\DateTimeInterface
    {
        return $this->date;
    }

    public function setDate(\DateTimeInterface $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getAuteur()
    {
        return $this->auteur;
    }

    public function setAuteur(string $auteur): self
    {
        $this->auteur = $auteur;

        return $this;
    }

    public function getNomCrypto(): ?string
    {
        return $this->nom_crypto;
    }

    public function setNomCrypto(string $nom_crypto): self
    {
        $this->nom_crypto = $nom_crypto;

        return $this;
    }
}

src/Form/CommentaireType.php
<?php

namespace App\Form;

use App\Entity\Commentaire;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('description')

        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Commentaire::class,
        ]);
    }
}

src/Controller/CommentairesController.php
<?php

namespace App\Controller;

use App\Entity\Commentaire;
use App\Form\Commentaire1Type;
use App\Repository\CommentaireRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("{_locale}/admin/commentaires")
 */
class CommentairesController extends AbstractController
{
    /**
     * @Route("/", name="commentaires_index", methods={"GET"})
     */
    public function index(CommentaireRepository $commentaireRepository): Response
    {
        return $this->render('commentaires/index.html.twig', [
            'commentaires' => $commentaireRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="commentaires_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $commentaire = new Commentaire();
        $form = $this->createForm(Commentaire1Type::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($commentaire);
            $entityManager->flush();

            return $this->redirectToRoute('commentaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaires/new.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaires_show", methods={"GET"})
     */
    public function show(Commentaire $commentaire): Response
    {
        return $this->render('commentaires/show.html.twig', [
            'commentaire' => $commentaire,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commentaires_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Commentaire $commentaire): Response
    {
        $form = $this->createForm(Commentaire1Type::class, $commentaire);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('commentaires_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('commentaires/edit.html.twig', [
            'commentaire' => $commentaire,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commentaires_delete", methods={"POST"})
     */
    public function delete(Request $request, Commentaire $commentaire): Response
    {
        if ($this->isCsrfTokenValid('delete'.$commentaire->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($commentaire);
            $entityManager->flush();
        }

        return $this->redirectToRoute('commentaires_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/commentaires/_delete_form.html.twig
<form method="post" action="{{ path('commentaires_delete', {'id': commentaire.id}) }}" onsubmit="return confirm('{% trans %}ComConfirmDel{% endtrans %}');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ commentaire.id) }}">
    <button class="btn text-danger"><i class="fa-solid fa-trash pr-2"></i>{% trans %}ComDelete{% endtrans %}</button>
</form>

templates/commentaires/_form.html.twig
{{ form_start(form) }}
{{'ComTitre'|trans({})}}
{{ form_widget(form.titre) }}
{{'ComDescription'|trans({})}}
{{ form_widget(form.description) }}
{{'ComAuteur'|trans({})}}
{{ form_widget(form.auteur) }}
<button class="text-success btn">
	<i class="fa-solid fa-check pr-2"></i>
	{% trans %}ComValid{% endtrans %}</button>
{{ form_end(form) }}

templates/commentaires/edit.html.twig
{% extends 'base.html.twig' %}

{% block container %}
    <h1>{% trans %}ComModif{% endtrans %} #{{commentaire.id}}</h1>

    {{ include('commentaires/_form.html.twig', {'button_label': 'Valider'}) }}

    <a class="ml-3" href="{{ path('commentaires_index') }}"><i class="fa-solid fa-angle-left mr-2"></i>{% trans %}ComBackToList{% endtrans %}</a>

    {{ include('commentaires/_delete_form.html.twig') }}
{% endblock %}

templates/commentaires/index.html.twig
{% extends 'base.html.twig' %}

{% block container %}
    <h1>{% trans %}ComPageTitre{% endtrans %}</h1>

    <table class="table">
        <thead>
            <tr>
                <th>{% trans %}ComId{% endtrans %}</th>
                <th>{% trans %}ComDescription{% endtrans %}</th>
                <th>{% trans %}ComDate{% endtrans %}</th>
                <th>{% trans %}ComTitre{% endtrans %}</th>
                <th>{% trans %}ComAuteur{% endtrans %}</th>
                <th>{% trans %}ComNomCrypto{% endtrans %}</th>
                <th>{% trans %}ComAction{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for commentaire in commentaires %}
            <tr>
                <td>{{ commentaire.id }}</td>
                <td>{{ commentaire.description }}</td>
                <td>{{ commentaire.date ? commentaire.date|date('Y-m-d') : '' }}</td>
                <td>{{ commentaire.titre }}</td>
                <td>{{ commentaire.auteur }}</td>
                <td>{{ commentaire.nomCrypto }}</td>
                <td>
                    <a href="{{ path('commentaires_show', {'id': commentaire.id}) }}"><i class="fa-solid fa-eye mr-2"></i></a>
                    <a href="{{ path('commentaires_edit', {'id': commentaire.id}) }}"><i class="fa-solid fa-pen"></i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="7">{% trans %}ComNoRecord{% endtrans %}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {# <a href="{{ path('commentaires_new') }}">Create new</a> #}
{% endblock %}

templates/commentaires/new.html.twig
{% extends 'base.html.twig' %}

{% block container %}
    <h1>{% trans %}ComCreate{% endtrans %}</h1>

    {{ include('commentaires/_form.html.twig') }}

    <a href="{{ path('commentaires_index') }}">{% trans %}ComBackToList{% endtrans %}</a>
{% endblock %}

templates/commentaires/show.html.twig
{% extends 'base.html.twig' %}

{% block container %}
    <h1>{% trans %}ComDetail{% endtrans %} #{{commentaire.id}}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>{% trans %}ComId{% endtrans %}</th>
                <td>{{ commentaire.id }}</td>
            </tr>
            <tr>
                <th>{% trans %}ComDescription{% endtrans %}</th>
                <td>{{ commentaire.description }}</td>
            </tr>
            <tr>
                <th>{% trans %}ComDate{% endtrans %}</th>
                <td>{{ commentaire.date ? commentaire.date|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>{% trans %}ComTitre{% endtrans %}</th>
                <td>{{ commentaire.titre }}</td>
            </tr>
            <tr>
                <th>{% trans %}ComAuteur{% endtrans %}</th>
                <td>{{ commentaire.auteur }}</td>
            </tr>
            <tr>
                <th>{% trans %}ComNomCrypto{% endtrans %}</th>
                <td>{{ commentaire.nomCrypto }}</td>
            </tr>
        </tbody>
    </table>

    <a class="ml-3" href="{{ path('commentaires_index') }}"><i class="fa-solid fa-angle-left mr-2"></i>{% trans %}ComBackToList{% endtrans %}</a>

    <a class="ml-3" href="{{ path('commentaires_edit', {'id': commentaire.id}) }}"><i class="fa-solid fa-pen mr-2"></i>{% trans %}ComChange{% endtrans %}</a>

    {{ include('commentaires/_delete_form.html.twig') }}
{% endblock %}